In [22]:
import streamlit as st
import pandas as pd
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import xgboost as xgb

The full dataset contains over 1.8 million records, which would slow down training and testing greatly to process in full. For the sake of our assignment, we will be only be taking 100000 random rows from the combined dataset.

In [26]:
# Filepaths

train_path = 'fraudTrain.csv'
test_path = 'fraudTest.csv'


# Load the files

df_train = pd.read_csv(train_path, index_col=0)
df_test = pd.read_csv(test_path, index_col=0)


# Combine into single dataframe

df = pd.concat([df_train, df_test], axis=0, ignore_index=True)


# Take a sample of 100000 rows

df = df.sample(100000, random_state=42)

In [27]:
df.head(10)

        trans_date_trans_time            cc_num  ...  merch_long is_fraud
1541144   2020-09-18 07:13:39  5359543825610251  ... -111.649432        0
1731581   2020-12-05 17:48:25  5540636818935089  ...  -71.008959        0
354659    2019-06-15 11:24:44  2720894374956739  ...  -83.508020        0
1493788   2020-08-29 22:50:25  6011438889172900  ...  -91.158293        0
468148    2019-07-25 15:50:35       60495593109  ...  -96.577001        0
1389854   2020-07-23 17:29:49  6011477612335392  ...  -84.030238        0
1760906   2020-12-11 23:06:59  2703186189652095  ...  -81.063288        0
469447    2019-07-26 04:56:44  4839615922685395  ...  -86.136019        0
1835018   2020-12-28 07:36:56  3553629419254918  ... -122.506513        0
240727    2019-04-30 15:08:10     4481131401752  ...  -72.593286        0

[10 rows x 22 columns]

In [28]:
df["merchant"] = df["merchant"].apply(lambda x : str(x).replace("fraud_", ""))

In [29]:
df.head()

        trans_date_trans_time            cc_num  ...  merch_long is_fraud
1541144   2020-09-18 07:13:39  5359543825610251  ... -111.649432        0
1731581   2020-12-05 17:48:25  5540636818935089  ...  -71.008959        0
354659    2019-06-15 11:24:44  2720894374956739  ...  -83.508020        0
1493788   2020-08-29 22:50:25  6011438889172900  ...  -91.158293        0
468148    2019-07-25 15:50:35       60495593109  ...  -96.577001        0

[5 rows x 22 columns]